
export const BUSINESS_UNITS = [
  'Operations',
  'Finance',
  'Sales and marketing',
  'Procurement',
  'Technology',
  'Human resources'
];

export const PRIORITY_LEVELS = ['LOW', 'MEDIUM', 'HIGH'];

export const INDUSTRIES = [
  'Public Sector',
  'Pharmaceuticals & Biotechnology',
  'Finance and Insurance',
  'Manufacturing',
  'Retail',
  'Construction',
  'Mining & Metals',
  'Agriculture',
  'Entertainment & Media',
  'Automotive',
  'Aerospace & Defense',
  'Chemicals',
  'Logistics and Transportation',
  'Real Estate',
  'IT and Telecom',
  'Human Resources (HR) & Recruitment',
  'Hospitality',
  'Environmental Services',
  'Energy and Utilities',
  'Hospitality & Tourism',
  'Healthcare',
  'Others'
];

export const CATEGORIES = [
  'Fertilizers',
  'Agricultural Equipment',
  'Infrastructure',
  'Bioinformatics',
  'Drug Development',
  'Defense Systems',
  'Gaming',
  'HR Outsourcing & Managed Services',
  'Animal Husbandry',
  'Travel and Tourism',
  'Food & Beverage',
  'Consumer Electronics',
  'Vehicle Manufacturing',
  'Recruitment & Talent Acquisition',
  'Aircraft Manufacturing',
  'Financial Services',
  'Film Production',
  'Water Management',
  'Software',
  'Supply Chain Management',
  'Capex & Opex',
  'Television Broadcasting',
  'Metal Processing',
  'Automotive',
  'Chemicals',
  'Aftermarket Services',
  'Space Exploration',
  'Event Management',
  'Industrial Equipment',
  'Renewable Energy',
  'Residential Construction',
  'Mineral Extraction',
  'Power Generation',
  'Consumer Goods',
  'Waste Management',
  'Oil and Gas',
  'E-commerce',
  'Education',
  'Medical Research',
  'Pollution Control',
  'Insurance',
  'Genomics',
  'Government Procurement',
  'Biotechnology',
  'Precious Metals',
  'Digital Media',
  'Fashion',
  'Real Estate Development',
  'Travel Services',
  'Hardware',
  'Food and Beverage',
  'Electronics',
  'Commercial Construction',
  'Financial Technology (Fintech)',
  'Consumer Chemicals',
  'HR Technology & Software (HR Tech)',
  'Basic Chemicals',
  'Telecommunications',
  'HR Consulting & Advisory',
  'Medical Equipment',
  'Banking',
  'Textiles',
  'Wholesale',
  'Property Management',
  'Heavy Machinery',
  'Accommodation Services',
  'Recycling Services',
  'Pharmaceuticals',
  'Packaging',
  'Freight and Shipping',
  'Food and Beverage Services',
  'Defense',
  'Environmental Consulting',
  'Crop Production',
  'Compliance & HR Legal Services',
  'Networking',
  'Non-metallic Minerals',
  'Logistics & Transportation',
  'Hotels and Resorts',
  'Food Processing',
  'Specialty Chemicals',
  'Automotive Technology',
  'Pharmaceuticals',
  'Hospital Supplies',
  'Aviation Services',
  'Warehousing',
  'Others'
];

export const CURRENCIES = [
  { label: 'Indian Rupee (INR)', value: 'INR' },
  { label: 'US Dollar (USD)', value: 'USD' },
  { label: 'Euro (EUR)', value: 'EUR' },
  { label: 'British Pound (GBP)', value: 'GBP' },
  { label: 'Japanese Yen (JPY)', value: 'JPY' },
  { label: 'Australian Dollar (AUD)', value: 'AUD' },
  { label: 'Canadian Dollar (CAD)', value: 'CAD' },
  { label: 'Swiss Franc (CHF)', value: 'CHF' },
  { label: 'Chinese Yuan (CNY)', value: 'CNY' },
  { label: 'Swedish Krona (SEK)', value: 'SEK' },
  { label: 'New Zealand Dollar (NZD)', value: 'NZD' },
  { label: 'Mexican Peso (MXN)', value: 'MXN' },
  { label: 'Singapore Dollar (SGD)', value: 'SGD' },
  { label: 'Hong Kong Dollar (HKD)', value: 'HKD' },
  { label: 'Norwegian Krone (NOK)', value: 'NOK' },
  { label: 'South Korean Won (KRW)', value: 'KRW' },
  { label: 'Turkish Lira (TRY)', value: 'TRY' },
  { label: 'Russian Ruble (RUB)', value: 'RUB' },
  { label: 'Brazilian Real (BRL)', value: 'BRL' },
  { label: 'South African Rand (ZAR)', value: 'ZAR' },
  { label: 'Philippine Peso (PHP)', value: 'PHP' },
  { label: 'Czech Koruna (CZK)', value: 'CZK' },
  { label: 'Indonesian Rupiah (IDR)', value: 'IDR' },
  { label: 'Malaysian Ringgit (MYR)', value: 'MYR' },
  { label: 'Hungarian Forint (HUF)', value: 'HUF' },
  { label: 'Icelandic Krona (ISK)', value: 'ISK' },
  { label: 'Danish Krone (DKK)', value: 'DKK' },
  { label: 'Thai Baht (THB)', value: 'THB' },
  { label: 'Polish Zloty (PLN)', value: 'PLN' },
  { label: 'Israeli Shekel (ILS)', value: 'ILS' },
  { label: 'United Arab Emirates Dirham (AED)', value: 'AED' },
  { label: 'Saudi Riyal (SAR)', value: 'SAR' },
  { label: 'Qatari Riyal (QAR)', value: 'QAR' },
  { label: 'Chilean Peso (CLP)', value: 'CLP' },
  { label: 'Colombian Peso (COP)', value: 'COP' },
  { label: 'Argentine Peso (ARS)', value: 'ARS' },
  { label: 'Vietnamese Dong (VND)', value: 'VND' },
  { label: 'Egyptian Pound (EGP)', value: 'EGP' },
  { label: 'Peruvian Sol (PEN)', value: 'PEN' },
  { label: 'Pakistani Rupee (PKR)', value: 'PKR' },
  { label: 'Bangladeshi Taka (BDT)', value: 'BDT' },
  { label: 'Sri Lankan Rupee (LKR)', value: 'LKR' },
  { label: 'Kenyan Shilling (KES)', value: 'KES' },
  { label: 'Ghanaian Cedi (GHS)', value: 'GHS' },
  { label: 'Nigerian Naira (NGN)', value: 'NGN' },
  { label: 'Tanzanian Shilling (TZS)', value: 'TZS' },
  { label: 'Ethiopian Birr (ETB)', value: 'ETB' },
  { label: 'Mauritian Rupee (MUR)', value: 'MUR' },
  { label: 'Moroccan Dirham (MAD)', value: 'MAD' },
  { label: 'Kazakhstani Tenge (KZT)', value: 'KZT' },
  { label: 'Uzbekistani Som (UZS)', value: 'UZS' },
  { label: 'Georgian Lari (GEL)', value: 'GEL' },
  { label: 'Lebanese Pound (LBP)', value: 'LBP' },
  { label: 'Jordanian Dinar (JOD)', value: 'JOD' },
  { label: 'Kuwaiti Dinar (KWD)', value: 'KWD' },
  { label: 'Bahraini Dinar (BHD)', value: 'BHD' },
  { label: 'Omani Rial (OMR)', value: 'OMR' },
  { label: 'Syrian Pound (SYP)', value: 'SYP' },
  { label: 'Sudanese Pound (SDG)', value: 'SDG' },
  { label: 'Tunisian Dinar (TND)', value: 'TND' },
  { label: 'Algerian Dinar (DZD)', value: 'DZD' }
];

export const UNITS_OF_MEASUREMENT = [
  { label: 'EA (Each)', value: 'EA' },
  { label: 'DZ (Dozen)', value: 'DZ' },
  { label: 'PR (Pair)', value: 'PR' },
  { label: 'SET (Set)', value: 'SET' },
  { label: 'LOT (Lot)', value: 'LOT' },
  { label: 'gm (Gram)', value: 'gm' },
  { label: 'kg (Kilogram)', value: 'kg' },
  { label: 'MT (Metric Ton)', value: 'MT' },
  { label: 'lb (Pound)', value: 'lb' },
  { label: 'mL (Milliliter)', value: 'mL' },
  { label: 'L (Liter)', value: 'L' },
  { label: 'm³ (Cubic Meter)', value: 'm³' },
  { label: 'gal (Gallon)', value: 'gal' },
  { label: 'cm (Centimeter)', value: 'cm' },
  { label: 'm (Meter)', value: 'm' },
  { label: 'in (Inch)', value: 'in' },
  { label: 'ft (Foot)', value: 'ft' },
  { label: 'yd (Yard)', value: 'yd' },
  { label: 'm² (Square Meter)', value: 'm²' },
  { label: 'ft² (Square Foot)', value: 'ft²' },
  { label: 'HR (Hour)', value: 'HR' },
  { label: 'D (Day)', value: 'D' },
  { label: 'MO (Month)', value: 'MO' },
  { label: 'YR (Year)', value: 'YR' },
  { label: 'BX (Box)', value: 'BX' },
  { label: 'CTN (Carton)', value: 'CTN' },
  { label: 'PK (Pack)', value: 'PK' },
  { label: 'RL (Reel)', value: 'RL' },
  { label: 'ROLL (Roll)', value: 'ROLL' },
  { label: 'Per Transaction', value: 'Per Transaction' },
  { label: 'PUPM (Per User / Per Month)', value: 'PUPM' },
  { label: 'Per Km / Per Ton', value: 'Per Km / Per Ton' },
  { label: 'LS (Lump Sum)', value: 'LS' },
  { label: 'NTE (Not To Exceed)', value: 'NTE' },
  { label: 'Milestone-Based', value: 'Milestone-Based' },
  { label: 'Per Implementation', value: 'Per Implementation' },
  { label: 'Per License', value: 'Per License' },
  { label: 'SLA-Based Unit', value: 'SLA-Based Unit' },
  { label: 'Others', value: 'Others' }
];
